[platformio]
default_envs = sensor_test
src_dir = .

[common]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_archive = false
lib_deps =
    askuric/Simple FOC@^2.2

[env:sensor_test]
extends = common
build_src_filter =
    -<*>
    +<V1_01_AS5600_Sensor_Test/V1_01_AS5600_Sensor_Test.ino>

[env:openloop_test]
extends = common
build_src_filter =
    -<*>
    +<V1_02_2804_OpenLoop_Test/V1_02_2804_OpenLoop_Test.ino>

[env:closedloop_velocity_test]
extends = common
build_src_filter =
    -<*>
    +<V1_03_ClosedLoop_Velocity_Test/V1_03_ClosedLoop_Velocity_Test.ino>
